### PR TITLE
Use defaults-extra-file instead of defaults-file

### PR DESCRIPTION
**Pull request by JustInVTime**

### CODE REVIEW

**Comment by renan** [comment]
Is it better? Safer?

**Comment by renan** [comment]
Does all MySQL servers accepts this property? What happens with older installations using this script?

**Comment by RBakkum** [comment]
```
–defaults-extra-file is used to tell a program to read a single specific option file in addition to the standard option files.
–no-defaults option is used to tell a program to ignore all option files.
```

So yes, it is better. I uses the login file in addition to other configuration files, instead of ignoring everything and just login. This could be settings for character-sets etc etc...

**Comment by renan** [comment]
Merged

**Pull request merged**
